# Generated by Django 5.0.6 on 2024-07-06 08:44

import django.db.models.deletion
import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=200)),
                ('debut', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=singer.models.image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('release', models.DateField()),
                ('content', models.TextField(max_length=200)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='singer.singer')),
            ],
        ),
        migrations.AddField(
            model_name='singer',
            name='tag',
            field=models.ManyToManyField(blank=True, to='singer.tag'),
        ),
    ]
